### ISSUE TITLE
데이터 준비

### ISSUE THREAD

**Issue by HyeonHeeDo** [Purifier-kr/Second_Project#2]
- [x] 기사 키워드 선정

- [x] 언론사 선정

- [x] 기사 크롤링

- [ ] 기사 분류

**Comment by MijeongJeon** [comment]
선정된 키워드들 여기에도 공유해주세요 👍

**Comment by Geonjae-Joo** [comment]
키워드:
1.  소득주도 성장
2. 최저임금
3. 코로나 정부 대응
4. 남북관계

**Comment by hoi-hoi-c** [comment]
언론사 선정:
동아일보
중앙일보

한겨레
경향신문
